---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.md"
exclude_paths:
- features/
